### ISSUE TITLE
Add Unattenuated Atmosphere to Secnario Resutls in Excel download.

### ISSUE THREAD

**Issue by rocketjay** [capecodcommission/watershed-mvp#178]

**Comment by ghost** [comment]
Since the other Scenario Results in the Excel sheet are driven by dbo.Scenario_Wiz, dbo.Scenario_Wiz needs an Nload_Atmosphere column which could be updated along with the other Nloads during apply/update/delete, then fed into a new cell in the spreadsheet.

I would need to add column dbo.Scenario_Wiz.Nload_Atmosphere, then UPDATE the column's value for a given scenario ID during any applyTreatment stored proc.
